### ISSUE TITLE
CheckIt links broken in activity books

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/library#224]
The links to the Precalculus exercises at https://tbil.org/library/ are not working. Neither are the ones in the book as they point there. The 2024 edition brings up a blank page and the preview one brings up a 404 error page.

**Comment by StevenClontz** [comment]
I know what's up... fix incoming

**Comment by StevenClontz** [comment]
All the banks were broken because I'm bad at computers, but now they should be fixed. Reopen if not.

**Comment by AbbyANoble** [comment]
The link in the preview section still does not work. 
<img width="300" alt="Screenshot 2024-08-07 at 2 49 22 PM" src="https://github.com/user-attachments/assets/7b717214-25f3-48fe-9a69-66ebcf82c180">

**Comment by StevenClontz** [comment]
Ah - our build process messes up the link: change https://tbil.org/preview/precalculus/exercises/#/bank/ to https://tbil.org/precalculus/preview/exercises/

I'll get that fixed...

**Comment by AbbyANoble** [comment]
What address should the sections in the book direct to? The 2024 edition goes to https://tbil.org/precalculus/2024/exercises/#/bank/EQ1/ (which gives an error). Will this fix update those?

**Comment by StevenClontz** [comment]
No effort required on your end - I'll fix it

**Comment by StevenClontz** [comment]
Ah, wait, no. We had to update the links to point to `library.tbil.org` for certain technical reasons.

I still should handle this fix myself, but it won't happen tonight. The links from <https://tbil.org/library> should be fixed soon though.

**Comment by AbbyANoble** [comment]
@StevenClontz bumping this! Check it links at the bottom of each section in https://library.tbil.org/2024/precalculus/frontmatter.html are not working.

**Comment by siwelwerd** [comment]
See #242, this affects all three books.

**Comment by jford1906** [comment]
I think the pull request I sent in to do this was merged? If so, we can close this.

**Comment by StevenClontz** [comment]
Closed by #480
